language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.2
before_script:
  - cp config/database.yml_travis config/database.yml
  - bundle exec rake db:create
addons:
  code_climate:
    repo_token: 32995bcb5d96dea952d8685dc9b68216105366a85d9d1d8f1416caeb259394b9
